spring.application.name=Subscription System

# MongoDB database name
#spring.data.mongodb.database=subscription-management-system

# Localhost connection
spring.data.mongodb.uri=mongodb://Nivetha:Admin%40123@127.0.0.1:27017/subscription-management-system?authSource=subscription-management-system
#spring.data.mongodb.uri=mongodb+srv://nivethaselvakumar23:Niveabi23@subscription.dnhpyfd.mongodb.net/subscription_db?appName=Subscription

# Disable JDBC auto config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt.secret=yF7pTz2V9kL3nXq8bA1mH5rS6dP4uE0cJ9oZxR2tWvU7yNqM3bL5hG8sF1dK6aT9

#Cron Job
cron.subscription.expiry=0 50 19 * * *
cron.subscription.run = false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nivethaselvakumar23@gmail.com
spring.mail.password=fxgj gnit yorc jxkx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Reminder cron (runs daily 7 AM)
cron.subscription.reminder=0 28 21 * * *
cron.subscription.reminder.run=false
